---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: VERSION          
          valueFrom:            
            resourceFieldRef:              
              containerName: webserver-simple              
              resource: image
